  version: '3'
    
  services:
    api-prod:
      build: .
      image: massenergize/api-prod
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/src
      ports:
        - "8000:8000"
